//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCDPatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCDPatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001=　
        ///0002=ぁ
        ///0003=あ
        ///0004=ぃ
        ///0005=い
        ///0006=ぅ
        ///0007=う
        ///0008=ぇ
        ///0009=え
        ///000A=ぉ
        ///000B=お
        ///000C=か
        ///000D=が
        ///000E=き
        ///000F=ぎ
        ///0010=く
        ///0011=ぐ
        ///0012=け
        ///0013=げ
        ///0014=こ
        ///0015=ご
        ///0016=さ
        ///0017=ざ
        ///0018=し
        ///0019=じ
        ///001A=す
        ///001B=ず
        ///001C=せ
        ///001D=ぜ
        ///001E=そ
        ///001F=ぞ
        ///0020=た
        ///0021=だ
        ///0022=ち
        ///0023=ぢ
        ///0024=っ
        ///0025=つ
        ///0026=づ
        ///0027=て
        ///0028=で
        ///0029=と
        ///002A=ど
        ///002B=な
        ///002C=に
        ///002D=ぬ
        ///002E=ね
        ///002F=の
        ///0030=は
        ///0031=ば
        ///0032=ぱ
        ///0033=ひ
        ///0034=び
        ///0035=ぴ
        ///0036=ふ
        ///0037=ぶ
        ///0038=ぷ
        ///0039=へ
        ///003A=べ
        ///003B=ぺ
        ///003C=ほ
        ///003D=ぼ
        ///003E=ぽ
        ///003F=ま
        ///0040=み
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chartable {
            get {
                return ResourceManager.GetString("chartable", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon irkick {
            get {
                object obj = ResourceManager.GetObject("irkick", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
